<main class="projet" id="projet">
    <section class="projets">
        <div class="projetContainer happyMessageGenerator">
            <h2>Happy Message Generator</h2>
            <p>Un generateur de message anime</p>
            <a title="voir projet HappyMessageGenerator" href="<?php echo getenv('MYSITE_URL'); ?>happymessagegenerator">Voir</a>
        </div>
        <div class="projetContainer meteoApp">
            <h2>Meteo</h2>
            <p>La meteo en utilisant l'api de openweathermap.org</p>
            <a title="voir projet MeteoApp" href="<?php echo getenv('MYSITE_URL'); ?>meteoapp">Voir</a>
        </div>
        <div class="projetContainer notePad">
            <h2>Notepad</h2>
            <p>Un Notepad avec authentification</p>
            <a title="voir projet de Notepad" href="<?php echo getenv('MYSITE_URL'); ?>notepad/home">Voir</a>
        </div>
        <div class="projetContainer moneyConvert">
            <h2>Convertisseur de devise</h2>
            <p>Un convertisseur de devise</p>
            <a title="voir projet de Notepad" href="<?php echo getenv('MYSITE_URL'); ?>moneyconvert">Voir</a>
        </div>

        <!-- <?php foreach ($projets as $key => $value) : ?>
        <div class=projetContainer>
            <h2><?php echo $value ?></h2>
            <p>description<p>
        </div>
    <?php endforeach; ?> -->

    </section>
</main>