<main id="moneyConvert">
    <div class="container">
        <label for="mon">
            <input type="number" id="input">
            <select name="current" id="cur">
                <option value="">--Choisissez une option--</option>
            </select>
            <select name="money" id="mon">
                <option value="">--Choisissez une option--</option>
            </select>
            <input type="text" id="convert" disabled="disabled">
        </label>
    </div>
    <noscript>
        <p>Veuillez activer javascript</p>
    </noscript>
    <script type="text/javascript" src="./public/js/MoneyConvert/script.js"></script>
</main>