<main id="notePad" class="notePad">
    <form method="post">
        <div class="">
            <label for="noteTitle">Title</label>
            <input type="text" name="noteTitle" id="noteTitle" required>
        </div>
        <div class="">
            <textarea id="noteContent" name="noteContent" rows="5" cols="33">
            </textarea>
        </div>
        <div class="submit">
            <button type="submit" name="submit">Save</button>
        </div>
    </form>
</main>