<main id="notePad">
    <section class="formContainer">
        <div class=iconContainer>
            <i class="fas fa-quote-right"></i>
        </div>
        <form  method="post">
            <div class="registerForm">
                <label for="email">Email</label>
                <input type="text" name="email" id="email" required>

            </div>
            <div class="registerForm">
                <label for="password">Password</label>
                <input type="password" name="password" id="password" required>
                <p><?php echo $errorMessage ?></p>
            </div>
            <div class="submit">
                <button type="submit" name="submit">Login</button>
            </div>
            <div class="submit">
                <a title="register" href="<?php echo getenv('MYSITE_URL'); ?>notepad/register">Register</a>
            </div>
        </form>
    </section>
</main>